# Generated by Django 3.0.8 on 2020-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_street_address1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripeid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
