# Generated by Django 3.0.8 on 2020-08-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200826_1252'),
        ('checkout', '0003_auto_20200826_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
