# Generated by Django 3.0.8 on 2020-08-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200826_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='training',
            new_name='product',
        ),
    ]
