# Generated by Django 3.0.8 on 2020-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('features', models.TextField(choices=[('free_initial', 'Free Initial 15 Minute Consult'), ('one_hour', 'One Hour of Games Based Training Sessions'), ('three_hours', 'Three Hours of Games Based Training Sessions'), ('five_hours', 'Five Hours of Games Based Training Sessions'), ('training_plan', 'Detailed Training Plan'), ('follow_up', 'Follow Up Phone Call'), ('facebook_group', 'Access To Private Facebook Training Group')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/products')),
            ],
        ),
    ]
