# Generated by Django 3.0.8 on 2020-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('features', models.TextField(choices=[('free_initial_15_minute_consult', 'Free Initial 15 Minute Consultation'), ('one_hour_of_games_based_training', 'One Hour of Games Based Training'), ('three_hours_of_games_based_training', 'Three Hours of Games Based Training'), ('five_hours_of_games_based_training', 'Five Hours of Games Based Training'), ('detailed_training_plan', 'Detailed Training Plan'), ('follow_up_phonecall', 'Follow Up Phonecall'), ('access_to_private_facebook_group', 'Access to Private Facebook Group')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/products')),
            ],
            options={
                'verbose_name_plural': 'Training Sessions',
            },
        ),
    ]
