# Generated by Django 3.0.8 on 2020-07-19 19:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('free_initial', 'Free 15 Minute Initial Consult'), ('one_hour', 'One Hour of Games Based Training Sessions'), ('three_hours', 'Three Hours of Games Based Training Sessions'), ('five_hours', 'Five Hours of Games Based Training Sessions'), ('training_plan', 'Detailed Training Plan'), ('follow_up', 'Follow Up Phone Call'), ('facebook_group', 'Access To Private Facebook Training Group')], max_length=83),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(upload_to='media/products'),
        ),
    ]
