# Generated by Django 3.0.8 on 2020-07-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200719_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='image',
        ),
    ]
